USEcodeup_test_db;

INSERTINTOalbums(artist,title,release_date,genre,sales)
VALUE('PinkFloyd','TheWall',1979,'ProgressiveRock', 19),
('Tom Petty and the Heart Breakers','Tom Petty and the Heart Breakers',1976,'Rock',19),
('Queen','A Night at The Opera',1975,'ProgressiveRock',19),
('MichaelJackson','Thriller',1982,'Pop, post-disco, funk, rock',66),
('AC/DC','BackinBlack',1980,'Hardrock',50),
('MeatLoaf','BatOutofHell',1977,'Hardrock, glamrock, progressiverock',50),
('PinkFloyd','TheDarkSideoftheMoon',1973,'Progressiverock',45),
('WhitneyHouston /Variousartists','TheBodyguard',1992,'R&B, soul, pop, soundtrack',45),
('Eagles','TheirGreatestHits(1971–1975)',1976,'Countryrock, softrock, folkrock',42),
('BeeGees /Variousartists','SaturdayNightFever',1977,'Disco',40),
('FleetwoodMac','Rumours',1977,'Softrock',40),
('ShaniaTwain','ComeOnOver',1997,'Country, pop',40),
('LedZeppelin','LedZeppelinIV',1971,'Hardrock, heavymetal, folkrock',37),
('MichaelJackson','Bad',1987,'Pop, rhythmandblues, funk and rock',35),
('AlanisMorissette','JaggedLittlePill',1995,'Alternativerock',33),
('MichaelJackson','Dangerous',1991,'Newjackswing, R&B and pop',32),
('CelineDion','FallingintoYou',1996,'Pop, softrock',32),
('Eagles','HotelCalifornia',1976,'Softrock',32),
('TheBeatles','Sgt.PeppersLonelyHeartsClubBand',1967,'Rock',32),
('Variousartists','DirtyDancing',1987,'Pop, rock, R&B',32),
('Adele','21',2011,'Pop, soul',31),
('Madonna','TheImmaculateCollection',1990,'Pop, dance',31),
('CelineDion','LetsTalkAboutLove',1997,'Pop, softrock',31),
('Metallica','Metallica',1991,'Heavymetal',31),
('TheBeatles','1',2000,'Rock',31),
('TheBeatles','AbbeyRoad',1969,'Rock',31),
('ABBA','Gold:GreatestHits',1992,'Pop, disco',30),
('BruceSpringsteen','BornintheU.S.A.',1984,'Heartlandrock',30),
('PinkFloyd','TheWall',1979,'Progressiverock',30),
('JamesHorner','Titanic:MusicfromtheMotionPicture',1997,'Filmscore',30),
('DireStraits','BrothersinArms',1985,'Rootsrock, bluesrock, softrock',30),
('Nirvana','Nevermind',1991,'Grunge, alternativerock',30),
('Santana','Supernatural',1999,'Latinrock',30),
('GunsNRoses','AppetiteforDestruction',1987,'Hardrock',30),
('EltonJohn','GoodbyeYellowBrickRoad',1973,'rock, poprock, glamrock',30);

